# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: types.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btypes.proto\x12\x13galaxis.site.health\"C\n\x11NodeDeviationData\x12\x0e\n\x06\x64iff_x\x18\x01 \x01(\x03\x12\x0e\n\x06\x64iff_y\x18\x02 \x01(\x03\x12\x0e\n\x06rotate\x18\x03 \x01(\x01\"\xa4\x01\n\x11MapNodeHealthInfo\x12\x0f\n\x07node_id\x18\x01 \x01(\x03\x12\x13\n\x0bmarker_code\x18\x02 \x01(\t\x12\x1b\n\x13\x64\x65\x63ode_success_rate\x18\x03 \x01(\x01\x12>\n\tdeviation\x18\x04 \x01(\x0b\x32&.galaxis.site.health.NodeDeviationDataH\x00\x88\x01\x01\x42\x0c\n\n_deviation\"2\n\x0ePositionData_t\x12\x0f\n\x07local_x\x18\x01 \x01(\x03\x12\x0f\n\x07local_y\x18\x02 \x01(\x03\"2\n\x0ePositionData_f\x12\x0f\n\x07local_x\x18\x01 \x01(\x01\x12\x0f\n\x07local_y\x18\x02 \x01(\x01\"\x8e\x03\n\x0f\x43urrentMarkData\x12\x0e\n\x06\x63\x61r_id\x18\x01 \x01(\x03\x12\x0f\n\x07node_id\x18\x02 \x01(\x03\x12\x13\n\x0bmarker_code\x18\x03 \x01(\t\x12\x46\n\x14\x63urrentlogiclocation\x18\x04 \x01(\x0b\x32#.galaxis.site.health.PositionData_tH\x00\x88\x01\x01\x12I\n\x17\x63urrentstandardlocation\x18\x05 \x01(\x0b\x32#.galaxis.site.health.PositionData_tH\x01\x88\x01\x01\x12I\n\x17\x63urrentcomputedlocation\x18\x06 \x01(\x0b\x32#.galaxis.site.health.PositionData_fH\x02\x88\x01\x01\x12\x16\n\x0e\x63urrent_degree\x18\x07 \x01(\x01\x42\x17\n\x15_currentlogiclocationB\x1a\n\x18_currentstandardlocationB\x1a\n\x18_currentcomputedlocation\"\x92\x01\n\x0e\x43odeHealthInfo\x12\x0e\n\x06\x63\x61r_id\x18\x01 \x01(\x03\x12\x0f\n\x07node_id\x18\x02 \x01(\x03\x12\x13\n\x0bmarker_code\x18\x03 \x01(\t\x12\x1b\n\x13\x64\x65\x63ode_success_rate\x18\x04 \x01(\x01\x12\x0e\n\x06\x64iff_x\x18\x05 \x01(\x03\x12\x0e\n\x06\x64iff_y\x18\x06 \x01(\x03\x12\r\n\x05\x61ngle\x18\x07 \x01(\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'types_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NODEDEVIATIONDATA._serialized_start=36
  _NODEDEVIATIONDATA._serialized_end=103
  _MAPNODEHEALTHINFO._serialized_start=106
  _MAPNODEHEALTHINFO._serialized_end=270
  _POSITIONDATA_T._serialized_start=272
  _POSITIONDATA_T._serialized_end=322
  _POSITIONDATA_F._serialized_start=324
  _POSITIONDATA_F._serialized_end=374
  _CURRENTMARKDATA._serialized_start=377
  _CURRENTMARKDATA._serialized_end=775
  _CODEHEALTHINFO._serialized_start=778
  _CODEHEALTHINFO._serialized_end=924
# @@protoc_insertion_point(module_scope)
